version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs: